version: '3'
services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
  celery:
    build: .
    command: celery -A scan_app worker -l info
    volumes:
        - .:/usr/src/app
  flower:
    build: .
    command: flower -A scan_app --port=5555
    ports:
      - 5555:5555
    volumes:
      - .:/usr/src/app
  rabbitmq:
    image: rabbitmq
    ports: 
      - 5672:5672