# Generated by Django 2.2.6 on 2019-10-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfile',
            old_name='lines',
            new_name='line_count',
        ),
    ]
